### ISSUE TITLE
Launchpad error no otocash repo

### ISSUE THREAD

**Issue by jaidetura55** [otocash/OTOCASH#2]
https://launchpad.net/ubuntu/+search?text=OTOCASH-qt
`https://launchpad.net/ubuntu/+search?text=OTOCASH-qt`
Your search for “OTOCASH-qt” did not return any results. You can search again including package descriptions.

**Comment by otocash** [comment]
Please see https://www.otocash.io/otocash_documentation/build-instructions-ubuntu16/
